name: Build Themes

on:
  workflow_dispatch:
  push:
    branches:
      - 'figma-tokens'
    paths:
      - 'libs/ui/styles/tokens.json'

jobs:
  build-themes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node/Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build themes
        run: yarn build:themes

      - uses: EndBug/add-and-commit@v7
        with:
          add: ./libs/ui/styles/themes
          message: 'Update themes from token file'
          default_author: github_actions

      - name: Create PR if it doesn't exist
        run: |
          if [[ $(gh pr list --json "url" -q ".[].url" --head figma-tokens | wc -c) -eq 0 ]]; then
            gh pr create --title "Autogenerate themes from new tokens" --body "This PR is generated by 'build-themes.yaml' when new changes are made to tokens.json"
          fi
